# Generated by Django 5.2.6 on 2025-09-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topnavbar',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
