# Generated by Django 5.2.6 on 2025-09-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_topnavbar_linkedin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='topnavbar',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
