# Generated by Django 5.2.6 on 2025-09-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/about'),
        ),
        migrations.AddField(
            model_name='about',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='images/about/signatures'),
        ),
    ]
