# Generated by Django 5.2.6 on 2025-09-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_about_image_about_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/services/logo')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/services/photos')),
            ],
        ),
    ]
