# Generated by Django 5.2.6 on 2025-09-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='logo',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
    ]
