# Generated by Django 5.2.6 on 2025-09-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_services_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_script', models.CharField(max_length=2555)),
                ('title', models.CharField(max_length=2555)),
                ('sub_script', models.TextField()),
                ('image', models.ImageField(upload_to='sliders/images')),
            ],
        ),
    ]
